version: '3'
services:
  envoy:
    image: envoyproxy/envoy
    ports:
      - "50099:50099"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  web:
    image: node:10
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - "./groceries-app:/app"
      - "/tmp/grpctinkering/node_modules_cache:/app/node_modules"
    working_dir: "/app"
    command: yarn start
    # Do this instead when there are dependency changes or on first run
    # command: yarn install
    tty: true

  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    expose:
      - "50042"
    ports:
      - "50042:50042"
    tty: true
    stdin_open: true
